name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]  # Ensure these Python versions exist and are compatible

    steps:
    - uses: actions/checkout@v4  # Check if v4 works, if not, try v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2  # Using @v2 for stable compatibility
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Tests
      run: |
        python manage.py test
